//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace parser.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class interes
    {
        public int Id { get; set; }
        public string Interes1 { get; set; }
    
        public virtual detailedinfo detailedinfo { get; set; }
    }
}
